build_image: freedomjs/freedom
language: node_js
node_js:
- 'stable'
- '4.2'
notifications:
  email:
    recipients:
      - freedom@cs.washington.edu
    on_success: change
    on_failure: always
before_install:
  - "export DISPLAY=:10.0"
  - "Xvfb :10 -screen 0 1280x1024x24 &"
install:
  - "google-chrome --version"
  - "firefox -v"
  - "shippable_retry npm install"
services:
  - mongodb
  - redis
script:
  - "gulp test"